name: Daily Balance Check

on:
  schedule:
    - cron: '0 6 * * *'  # Täglich um 06:00 UTC
  workflow_dispatch:

jobs:
  compare-balances:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install --no-cache-dir pandas==2.0.3 numpy==1.24.3

    - name: Run Update Loan
      run: python update_loan.py

    - name: Run Comparison
      run: python compare_balances.py

    - name: Check File Existence
      id: check_file
      run: |
        if [ -f lametric.json ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Debug Directory
      run: ls -la

    - name: Commit Changes
      if: steps.check_file.outputs.exists == 'true'
      run: |
        git config --global user.name "GitHub Bot"
        git config --global user.email "gh-bot@noreply.com"
        git add lametric.json
        git commit -m "Auto-update $(date +'%Y-%m-%d')" || exit 0
        git push
