# .github/workflows/update.yml
name: Daily Run

on:
  schedule:
    - cron: '0 6 * * *'  # 06:00 UTC
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir numpy==1.26.4 pandas==2.0.3

      - name: Run Comparison
        env:
          LOAN_BALANCE: ${{ secrets.LOAN_BALANCE }}
        run: python compare_balances.py

      - name: Commit Result
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "gh-bot@noreply.com"
          git add lametric.json
          git commit -m "Auto-update $(date +'%Y-%m-%d')" || exit 0
          git push
